### ISSUE TITLE
Create table to keep track of number of training tasks completed and try to integrate with scoreboard and/or first training task (Ben)

### ISSUE THREAD

**Issue by jacondel** [jacondel/memory1#7]

**Comment by benriexinger** [comment]
Use the following function at the end of all training methods.

cbTraining = function() {};
addTrainAttemptToDBSuccess(uEMail,map,"1",time,cbTraining);

uEMail = email address of user
map = the string of the map (ie. 2,3,4,6,3,1,5,6)
"1" = "the number or your training method
time = the total time taken to complete the training activity (a double in seconds)
